workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: dev

# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-


      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: yarn test src/logic/ticTacToe.test.js
      - run: yarn test src/api/index.test.js

      - run:
          name: Running code coverage to coveralls.io
          command: 'npm run server-test'
      
      - run:
          name: Creating PDF artifact
          command: 'npm run create-docs'
      - store_artifacts:
          path: docs/pdf/ 

          
        deploy:
          docker:
          - image: buildpack-deps:trusty
          steps:
            - checkout
            - run:
                name: Deploy dev to Heroku
                command: |
                  git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
            - run: yarn test src/E2ETesting/puppeteer.test.js
            
test:
  override:
  - bundle exec rake circleci:
      parallel: false
      timeout: 900

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=RZVVZMAJchArrFkoCN7tPxuu1OSJCf0Gv